version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn gregory_aparments.wsgi --bind 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    volumes:
       - static_volume:/home/app/staticfiles/
  
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data: