# Generated by Django 3.2.7 on 2022-11-21 08:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='ΚΑΤΑΣΤΑΣΗ')),
                ('category', models.CharField(choices=[('1', 'ΒΑΣΙΚΟ ΑΡΙΣΤΕΡΑ => (845*815)'), ('b', 'ΒΑΣΙΚΟ ΔΕΞΙΑ => (845*815)'), ('2', 'Second Banner')], default='1', max_length=1, verbose_name='ΚΑΤΗΓΟΡΙΑ')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='ΕΙΚΟΝΑ')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('a', 'Γενική Ερώτηση - General question'), ('b', 'Κρατήσεις - Booking Info')], max_length=1, null=True, verbose_name='Κατηγορία')),
                ('title', models.CharField(max_length=200, verbose_name='Θέμα')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ονοματεπώνυμο')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Τηλέφωνο')),
                ('text', tinymce.models.HTMLField(verbose_name='Μήνυμα')),
                ('is_readed', models.BooleanField(default=False, verbose_name='ΔΙΑΒΑΣΜΕΝΟ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_readed'],
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('url', models.TextField(null=True)),
            ],
        ),
    ]
