# Generated by Django 3.2.7 on 2022-11-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('1', 'ΒΑΣΙΚΟ ΑΡΙΣΤΕΡΑ => (845*815)'), ('b', 'ΒΑΣΙΚΟ ΔΕΞΙΑ => (845*815)'), ('2', 'Second Banner'), ('3', 'About Page')], default='1', max_length=1, verbose_name='ΚΑΤΗΓΟΡΙΑ'),
        ),
    ]
