# Generated by Django 3.2.7 on 2022-11-21 08:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Τίτλος')),
                ('title_eng', models.CharField(max_length=200, unique=True, verbose_name='Τίτλος Αγγλικα')),
            ],
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Κατάσταση')),
                ('image', models.ImageField(help_text='500*500', null=True, upload_to='discovers/')),
                ('big_image', models.ImageField(help_text='1200*500', null=True, upload_to='big_images/discovers/')),
                ('is_favorite', models.BooleanField(default=True, verbose_name='Προτεινόμενο')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Τίτλος')),
                ('text', tinymce.models.HTMLField(verbose_name='Περιγραφή')),
                ('title_eng', models.CharField(max_length=2000, unique=True, verbose_name='Τίτλος στα Αγγλικά')),
                ('text_eng', tinymce.models.HTMLField(verbose_name='Περιγραφή στα Αγγλικά')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=240, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discover.discovercategory')),
            ],
        ),
    ]
