# Generated by Django 3.2.7 on 2022-11-30 08:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='ΤΙΤΛΟΣ ΣΤΑ ΕΛΛΗΝΙΚΑ')),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(upload_to='news_letter_images')),
                ('text', tinymce.models.HTMLField(null=True, verbose_name='ΚΕΙΜΕΝΟ ΣΤΑ ΕΛΛΗΝΙΚΑ')),
                ('title_eng', models.CharField(max_length=200, unique=True, verbose_name='ΤΙΤΛΟΣ ΣΤΑ ΑΓΓΛΙΚΑ')),
                ('text_eng', tinymce.models.HTMLField(null=True, verbose_name='ΚΕΙΜΕΝΟ ΣΤΑ ΑΓΓΛΙΚΑ')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('cell_phone', models.CharField(blank=True, max_length=200)),
                ('acceptRules', models.BooleanField(default=False)),
                ('newsletterPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletterpage')),
            ],
        ),
    ]
