# Generated by Django 3.2.7 on 2022-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartitle',
            name='category',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='title_eng',
            field=models.CharField(max_length=220, null=True, verbose_name='ΤΙΤΛΟΣ'),
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='rooms',
        ),
        migrations.AddField(
            model_name='characteristic',
            name='rooms',
            field=models.ManyToManyField(null=True, related_name='chars', to='rooms.Room', verbose_name='ΔΩΜΑΤΙΟ'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='title',
            field=models.CharField(max_length=220, null=True, verbose_name='ΤΙΤΛΟΣ'),
        ),
        migrations.DeleteModel(
            name='CharacteristicsCategory',
        ),
        migrations.DeleteModel(
            name='CharTitle',
        ),
    ]
