# Generated by Django 3.2.7 on 2022-12-14 07:31

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20221208_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='extra_image',
            field=models.ImageField(blank=True, null=True, upload_to=rooms.models.extra_upload_photo),
        ),
        migrations.AddField(
            model_name='room',
            name='extra_text_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='extra_text_gr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_size',
            field=models.CharField(choices=[('1', '1 ΔΙΠΛΟ ΚΡΕΒΑΤΙ'), ('2', 'ΜΟΝΟ ΚΡΕΒΑΤΙ'), ('3', '1 ΔΙΠΛΟ ΚΡΕΒΑΤΙ-ΚΑΝΑΠΕΣ ΚΡΕΒΑΤΙ'), ('4', '1 ΔΙΠΛΟ ΚΡΕΒΑΤΙ ΚΑΙ 2 ΜΟΝΑ ΚΡΕΒΑΤΙΑ')], default='1', max_length=1, verbose_name='ΠΕΡΙΓΡΑΦΗ ΚΡΕΒΑΤΙΩΝ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_size_eng',
            field=models.CharField(choices=[('1', '1 DOUBLE BED'), ('2', 'SINGLE BED'), ('3', '1 DOUBLE BED -SOFA BED'), ('4', '1 DOUBLE DED AND 2 SINGLE BEDS')], default='1', max_length=1, verbose_name='ΠΕΡΙΓΡΑΦΗ ΚΡΕΒΑΤΙΩΝ ENG'),
        ),
    ]
