# Generated by Django 3.2.7 on 2022-12-14 07:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20221214_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='extra_text_eng',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_text_gr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
